F19/changes user field
i-barysiuk/bstu-curators pull request #23
Opened 2019-07-21 15:39 UTC by mishagitwork

2019-07-21 18:29 UTC, i-barysiuk requested changes
Change create service

2019-07-22 12:01 UTC, M-Kulinkovich approved these changes

2019-07-23 14:37 UTC, vol4k approved these changes

2019-07-24 13:37 UTC, mishagitwork commented
> Change create service

>Fixed

2019-07-24 19:11 UTC, i-barysiuk requested changes

2019-07-24 19:11 UTC, i-barysiuk commented on server/db/migrations/20190721145200-add_fields_user.js
> +
Все что выше не нужно
На одну миграцию только один модуль експорт

2019-07-25 15:24 UTC, merged