added adaptation for small devices
i-barysiuk/bstu-curators pull request #37
Opened 2019-07-31 19:04 UTC by s1ncereboy

2019-08-01 16:27 UTC, i-barysiuk requested changes

2019-08-01 16:27 UTC, i-barysiuk commented on app/src/components/tips/style.module.scss
> +@media screen and (max-width: 700px) {
dont change common components

2019-08-01 16:27 UTC, i-barysiuk commented on app/src/views/login/Login.jsx
> +            <p>
remove <p></p> or apply class name on it

2019-08-01 16:27 UTC, i-barysiuk commented on app/src/views/login/style.module.scss
> +    width: 130px;
use scss variables

2019-08-02 18:35 UTC, vol4k approved these changes

2019-08-03 10:37 UTC, merged